### ISSUE TITLE
Search results include advertisements

### ISSUE THREAD

**Issue by rgregg** [knative/website#23]
When we do a search, ads for related terms appear on the search page. We should be able to opt out of those.

https://www.knative.dev/search/?q=testing

**Comment by RichieEscarez** [comment]
Blocking item: knative specific `@gmail.com` account

**Comment by rgregg** [comment]
Does the email address get published anywhere? We should probably create a knative-website Google Group that's shared among the WG leads for this purpose.

**Comment by RichieEscarez** [comment]
I suppose the address could be published but the idea is to create a single/separate account that we can tie the Custom Search Engine account to (and I suppose we would also tie it to the Analytics account).

**Comment by RichieEscarez** [comment]
I tried to create a new gmail account, specifically "knative@gmail.com" but it already exists and I'm wondering if we own that before trying to create another account? 

Something like a Google Group address wont work because it still gets tied to a specific email account (you can assign owners but you need to sign in with a user account to create the group in the first place).

If we dont know who owns knative@gmail.com, do any of these addresses work? Any other suggestions?
- knative-website@
- knative.dev@

**Comment by RichieEscarez** [comment]
Fixed: https://github.com/knative/website/pull/34
