### ISSUE TITLE
Docs version switcher uses both "development" and "Pre-release"

### ISSUE THREAD

**Issue by bbrowning** [knative/website#31]
In the dropdown of the version switcher, it lists "development" to see in-progress docs for the upcoming release. But, if you choose that version, the title of that same version switcher says "Pre-release". Should we choose just one of those terms and use it consistently in the version switcher?

**Comment by RichieEscarez** [comment]
This was an intentional effort to "quickly" deliver a clear message that the "development" section of the site is a "pre-release" version (the goal was to be as obvious as possible and "pre-release" was more intuitive). To use "pre-release" everywhere, is to change the URL/folder name where the content gets hosted (thus the quick change in just the label).

We are worried that since most of the other OSS docs site host "master" content in a completely separate sub-domain, that its likely users might stumble into the wrong section on our site.

We are focused on other priority items right now but will definitely come back to this soon. Since this is closely related to #25, for efficiency, ill try to address the long term solutions at the same time.

@bbrowning While this has not yet been fully discussed in the Docs WG, what would your preference be?
1. change the URL and all labels to pre-release -> ...knative.dev/**pre-release**/...
2. host master is a different sub-domain -> https:///**development**.knative.dev/docs
3. do you have other suggestions?

The consensus from the small circles where this was brought up, is that regardless where the content lives in the site and under whatever URL, that we modify the CSS with some type of banner or different color to obviously clarify "pre-release content".

**Comment by bbrowning** [comment]
I agree that we don't want users stumbling into the wrong section of the website. The easiest thing may be to just entirely remove references to pre-release docs from knative.dev and move them to a subdomain as that gives you maximum flexibility in pre-release docs styling and warnings that this isn't for official releases.
